spring:
  application:
    name: device-management

  datasource:
    url: jdbc:postgresql://localhost:5432/device_management
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
        retry.backoff.ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: "*"  # SÃ³ o essencial

  metrics:
    tags:
      application: device-management
      environment: local

resilience4j:
  retry:
    instances:
      retry_device_is_present:
        max-attempts: 3
        wait-duration: 5s

      retry_for_all_devices:
        max-attempts: 3
        wait-duration: 5s

  circuitbreaker:
    instances:
      circuitbreaker_device_is_present:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException
        ignore-exceptions:
          - br.com.device_management.infra.exceptions.ServiceUnavailable
          - br.com.device_management.infra.exceptions.DeviceIsPresent

      circuitbreaker_kafka_send_event:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.kafka.KafkaException

      circuitbreaker_for_get_all_devices:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException




server:
  port: 8082
public:
  key: classpath:public-key

