spring:
  application:
    name: device-management

  datasource:
    url: jdbc:postgresql://localhost:5432/device_management
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8080
public:
  key: classpath:public-key

