spring:
  application:
    name: sensor-test
  datasource:
    url: jdbc:postgresql://localhost:5432/sensor_test
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        spring.json.add.type.headers: false
        retry.backoff.ms: 5000
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    tags:
      application: sensor-test
      environment: local

resilience4j:
  retry:
    instances:
      retry_sensor_is_empty: #OK
        max-attempts: 3
        wait-duration: 5s

      retry_sensor_is_present: #OK
        max-attempts: 3
        wait-duration: 5s

      retry_get_all_sensors: #OK
        max-attempts: 3
        wait-duration: 5s

  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3

    instances:
      circuitbreaker_sensor_is_empty: #OK
        base-config: default
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException
        ignore-exceptions:
          - br.com.sensor_test.infra.exceptions.ServiceUnavailableException

      circuitbreaker-sensor_is_present: #OK
        base-config: default
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException
        ignore-exceptions:
          - br.com.sensor_test.infra.exceptions.ServiceUnavailableException

      circuitbreaker_get_all_sensors: #OK
        base-config: default
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      circuitbreaker_scheduling: #OK
        base-config: default
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      circuitbreaker_kafka_producer: #OK
        base-config: default
        record-exceptions:
          - org.springframework.kafka.KafkaException
          - org.apache.kafka.common.errors.TimeoutException
        ignore-exceptions:
          - br.com.sensor_test.infra.exceptions.ServiceUnavailableException

      circuitbreaker_kafka_consumer: #OK
        base-config: default
        record-exceptions:
          - org.springframework.kafka.KafkaException
          - org.apache.kafka.common.errors.TimeoutException

server:
  port: 8083

public:
  key: classpath:public-key