spring:
  application:
    name: device-login
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # SÃ³ o essencial

  metrics:
    tags:
      application: device-login
      environment: local

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    lease-renewal-interval-in-seconds: '5'
    lease-expiration-duration-in-seconds: '10'

resilience4j:
  circuitbreaker:
    instances:
      DEVICE-USER:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - feign.FeignException
          - java.net.ConnectException
          - java.net.SocketTimeoutException

public:
  key: classpath:public-key
private:
  key: classpath:private-key

server:
  port: 8081
  error:
    include-stacktrace: never
    include-message: never

logging:
  level:
    br.com.device_login.infra.client.UserClient: DEBUG
    feign: DEBUG
    org.springframework.cloud.openfeign: DEBUG