spring:
  application:
    name: device-login

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    tags:
      application: device-login
      environment: local

resilience4j:
  circuitbreaker:
    instances:
      circuitbreaker_feign:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - java.lang.RuntimeException
          - feign.FeignException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
        ignore-exceptions:
          - br.com.device_login.infra.exceptions.ServiceUnavailableException