spring:
  application:
    name: device-user

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/device_user}
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Só o essencial

  metrics:
    tags:
      application: device-user
      environment: local

resilience4j:
  retry:
    instances:
      user-retry:  # ← Nome do @Retry
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - java.net.ConnectException
          - java.net.SocketTimeoutException
        ignore-exceptions:
          - br.com.device_user.infra.exceptions.UserNotFoundException

  circuitbreaker:
    instances:
      circuitbreaker_for_database:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException
        ignore-exceptions:
          - br.com.device_user.infra.exceptions.ServiceUnavailableException
          - br.com.device_user.infra.exceptions.UserNotFoundException

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    lease-renewal-interval-in-seconds: '5'
    lease-expiration-duration-in-seconds: '10'

public:
  key: classpath:public-key

server:
  port: 8080