spring:
  application:
    name: device-notification
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/device_notification}
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
    fetch-registry: 'true'
    register-with-eureka: 'true'
  instance:
    lease-renewal-interval-in-seconds: '5'
    lease-expiration-duration-in-seconds: '10'

resilience4j:
  retry:
    instances:
      retry_notifications:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      retry_occult_notifications:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      retry_visualisation:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      retry_occult:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      retry_count:
        max-attempts: 3
        wait-duration: 5s
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

  circuitbreaker:
    instances:
      circuitbreaker_notifications:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      circuitbreaker_occult_notifications:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      circuitbreaker_visualisation:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

      circuitbreaker_occult:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException
        ignore-exceptions:
          - br.com.device_notification.infra.exceptions.NotificationNotFoundEx

      circuitbreaker_count:
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - org.springframework.dao.DataAccessException
          - org.springframework.dao.DataAccessResourceFailureException

public:
  key: classpath:public-key

server:
  port: 8085
  error:
    include-stacktrace: never
    include-message: never